language: python
python:
  - "3.4"
services:
  - redis
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=geoip
  - coverage report -m
after_success:
  - pip install coveralls
  - coveralls
